[package]
name = "wgpu-example-01-hello-compute"
edition = "2024"
rust-version = "1.85.0"
publish = false

[dependencies]
bytemuck = "1.23.1"
env_logger = "0.11.8"
pollster = "0.4.0"

[dependencies.wgpu]
path = "../../.."
