[package]
name = "wgpu-example-02-hello-window"
edition = "2024"
rust-version = "1.85.0"
publish = false

[dependencies]
env_logger = "0.11.8"
pollster = "0.4.0"

[dependencies.wgpu]
path = "../../.."

[dependencies.winit]
version = "0.30.12"
features = [ "android-native-activity",]
