[package]
name = "naga-xtask"
version = "0.1.0"
edition = "2024"
publish = false
rust-version = "1.85.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
anyhow = "1.0.100"
env_logger = { version = "0.11.8", default-features = false }
glob = "0.3.3"
hlsl-snapshots = { path = "../hlsl-snapshots" }
indicatif = "0.18.0"
jobserver = "0.1.34"
log = "0.4.28"
num_cpus = "1.17.0"
pico-args = "0.5.0"
shell-words = "1.1.0"
which = "8.0.0"


